# Generated by Django 3.2.12 on 2022-02-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220227_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('name',), 'verbose_name': 'Издатель', 'verbose_name_plural': 'Издатели'},
        ),
    ]
