# Generated by Django 3.2.12 on 2022-03-10 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('due_to', models.DateTimeField()),
                ('owner', models.CharField(max_length=50)),
                ('is_done', models.BooleanField()),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.todolistmodel')),
            ],
        ),
    ]
