# Generated by Django 3.2.12 on 2022-03-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name': 'To Do task', 'verbose_name_plural': 'To Do tasks'},
        ),
        migrations.AlterModelOptions(
            name='todolistmodel',
            options={'verbose_name': 'To Do list', 'verbose_name_plural': 'To Do lists'},
        ),
    ]
