# Generated by Django 3.2.12 on 2022-05-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_taskmodel_todo_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoListGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
