# Generated by Django 3.2.12 on 2022-05-04 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_todolistgroupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistmodel',
            name='todo_list_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to='main.todolistgroupmodel'),
        ),
    ]
