# Generated by Django 3.2.12 on 2022-05-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_todolistmodel_todo_list_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
